### ISSUE TITLE
Generating with single close xml tags

### ISSUE THREAD

**Issue by mixxer** [Pelagicore/gdbus-codegen-glibmm#77]
`<?xml version="1.0"?>
<!DOCTYPE node PUBLIC "-//freedesktop//DTD D-BUS Object Introspection 1.0//EN" "http://www.freedesktop.org/standards/dbus/1.0/introspect.dtd">
<node>
  <interface name="org.freedesktop.DBus.Introspectable">
    <method name="Introspect">
      <arg name="xml" type="s" direction="out"/>
    </method>
  </interface>
  <interface name="org.ofono.Manager">
    <method name="GetModems">
      <arg name="modems" type="a(oa{sv})" direction="out"/>
    </method>
    <signal name="ModemAdded">
      <arg name="path" type="o"/>
      <arg name="properties" type="a{sv}"/>
    </signal>
    <signal name="ModemRemoved">
      <arg name="path" type="o"/>
    </signal>
  </interface>
  <interface name="org.ofono.HandsfreeAudioManager">
    <method name="GetCards">
      <arg name="cards" type="a{oa{sv}}" direction="out"/>
    </method>
    <method name="Register">
      <arg name="path" type="o" direction="in"/>
      <arg name="codecs" type="ay" direction="in"/>
    </method>
    <method name="Unregister">
      <arg name="path" type="o" direction="in"/>
    </method>
    <signal name="CardAdded">
      <arg name="path" type="o"/>
      <arg name="properties" type="a{sv}"/>
    </signal>
    <signal name="CardRemoved">
      <arg name="path" type="o"/>
    </signal>
  </interface>
  **<node name="bluetooth"/>**
</node>`

I got a problem with a single closing tag.

**Comment by mardy** [comment]
Hi! I just tried, and it seems to be working fine here. What error do you get, exactly?

**Comment by mixxer** [comment]
Hi, mardy

The following error message occurred;; 

gdbus-codegen-glibmm3 --generate-cpp-code=dbus-ofono org.ofono.xml

Traceback (most recent call last):
  File "/usr/local/bin/gdbus-codegen-glibmm3", line 11, in <module>
    load_entry_point('gdbus-codegen.glibmm==2.99.0', 'console_scripts', 'gdbus-codegen-glibmm3')()
  File "/usr/local/lib/python3.6/dist-packages/gdbus_codegen.glibmm-2.99.0-py3.6.egg/codegen_glibmm/codegen_main.py", line 82, in codegen_main
    parsed_ifaces = parser.parse_dbus_xml(xml_data)
  File "/usr/local/lib/python3.6/dist-packages/gdbus_codegen.glibmm-2.99.0-py3.6.egg/codegen_glibmm/parser.py", line 223, in parse_dbus_xml
    parser = DBusXMLParser(xml_data)
  File "/usr/local/lib/python3.6/dist-packages/gdbus_codegen.glibmm-2.99.0-py3.6.egg/codegen_glibmm/parser.py", line 55, in __init__
    self._parser.Parse(xml_data)
  File "../Modules/pyexpat.c", line 414, in StartElement
  File "/usr/local/lib/python3.6/dist-packages/gdbus_codegen.glibmm-2.99.0-py3.6.egg/codegen_glibmm/parser.py", line 109, in handle_start_element
    self._cur_object.doc_string = self._last_comment
**AttributeError: 'NoneType' object has no attribute 'doc_string'**

As mentioned earlier, after I remove a single close tag, the error is cleared.... 

Thank you and Best Regards.

**Comment by mardy** [comment]
Thanks! Could you also share the `org.ofono.xml` file?
